### ISSUE TITLE
一部のレコードで、英語表記の市区町村区分が途切れている

### ISSUE THREAD

**Issue by kidmin** [ttskch/jp-postal-code-api#1]
# バグの内容

- 一部のレコードで、英語表記の市区町村名が途切れている
  - 例: `963-5118` （福島県東白川郡矢祭町東舘）で、「町」のローマ字読み「machi」が途切れて「mach」になっている: `Yamatsuri-mach`
  - 例: `585-0041` （大阪府南河内郡千早赤阪村水分）で、「村」のローマ字読み「mura」が途切れて「mu」になっている: `Chihayaakasaka-mu`

# 本来どう動作すべきか

- 英語表記の市区町村名が途切れずに記載されている
  - 上記の例ではそれぞれ `Yamatsuri-machi` と `Chihayaakasaka-mura`

# 参考情報

## データが欠けている原因

元データである [住所の郵便番号（ローマ字）（CSV 形式）](https://www.post.japanpost.jp/zipcode/dl/roman-zip.html) を郵便局 Web サイトからダウンロードして確認したところ、同じように途切れていることが分かりました。これは、 [郵便番号データ（ローマ字）の説明](https://www.post.japanpost.jp/zipcode/dl/readme_ro.html) ページの「留意点」に記載されている通り、半角フィールド長の上限 35 文字を超えてしまっているためです。

元データのカタカナから郵便局のページに記載されているアルゴリズムでローマ字表記に変換し直す、または、元データの段階で欠落しているため、制限事項としてドキュメントに一部が欠けている可能性があることを記載する、といった修正が考えられます。

## 類似バグ

https://github.com/geolonia/japanese-addresses/issues/118

**Comment by ttskch** [comment]
@kidmin ご指摘ありがとうございます！

現時点では基本的に元データの内容をそのまま配信するスタンスをとりたいと考えているため、今回は対応としては [READMEへの記載](https://github.com/ttskch/jp-postal-code-api/commit/79cd8116288a7f5b05c0c9941d4d215ce145f8b7) に留めることにしました🙏
