### ISSUE TITLE
町域名に「一円」の正規表現式の不備可能

### ISSUE THREAD

**Issue by Ruoyu05** [ttskch/jp-postal-code-api#2]
郵便局の公式サイトで、データの格納イメージについて説明より、
4) の項目位置に、「"○○市（又は町・村）一円"」とは、町域名がない市区町村の場合にお書きいただく番号です。

特別なデータがあります。
〒5220317 滋賀県 犬上郡 多賀町 一円

このデータから、「町域名がない市区町村」として考えることはできないと思います。
実際に Google マップで検索すると、滋賀県犬上郡多賀町には、「一円」という地名が存在するようです。
したがって、正規表現式を以下のように修正することをご検討してお願いします。
'/.*一円$/'  -> '/.+一円$/' 
'/.*ichien$/i'  ->  '/.+ichien$/i'

**Comment by ttskch** [comment]
@Ruoyu05 おお〜！情報ありがとうございます！修正しました！

https://jp-postal-code-api.ttskch.com/api/v1/5220317.json
